project_id = "nawdvulumebqbxmkedzw"

[functions.manage-events]
verify_jwt = false

[functions.submit-event]
verify_jwt = false

[functions.scan-event-flyer]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false