-- Add week of October 20-26, 2025 events (excluding Community Music Hangout)
-- Note: PDT (UTC-7) applies for these dates

-- Monday, October 20, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Storytime for Families', 'Ortega Branch Library (3223 Ortega St)', '2025-10-20', '2025-10-20 17:30:00+00', '2025-10-20 18:00:00+00', 'Early Childhood/Family', 'A morning storytime with books, songs, and rhymes for children of all ages. Free drop-in event (no registration required).', 'approved'),
('Homework Help', 'Ortega Branch Library (3223 Ortega St)', '2025-10-20', '2025-10-20 22:30:00+00', '2025-10-21 00:30:00+00', 'Academic/Youth', 'After-school tutoring by Tutoring By The Bay volunteers for elementary and middle school students. Help with all core subjects; first-come, first-served. Free program in the library''s meeting room.', 'approved');

-- Tuesday, October 21, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Storytime for Toddlers', 'Ortega Branch Library (3223 Ortega St)', '2025-10-21', '2025-10-21 17:30:00+00', '2025-10-21 18:00:00+00', 'Early Childhood', 'Storytime featuring books, songs, movement and more for toddlers (16 months to 2 years) with their caregivers. Free library event.', 'approved'),
('College on the Mind Parent Series', 'Black Bird Bookstore & Café (4541 Irving St)', '2025-10-21', '2025-10-22 02:00:00+00', '2025-10-22 03:30:00+00', 'Educational Workshop', 'An evening talk for parents of high school students on the college admissions mindset and process. Hosted at the Black Bird community bookstore; free to attend (café open for purchases).', 'approved');

-- Wednesday, October 22, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('After Hours Reading Club', 'Black Bird Bookstore (4541 Irving St)', '2025-10-22', '2025-10-23 02:00:00+00', '2025-10-23 04:00:00+00', 'Book Club', 'Black Bird After Hours Reading Club meeting in the bookstore after closing time. An open community book discussion (title or theme announced by the store; all are welcome). Free.', 'approved');

-- Thursday, October 23, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Author Event: Mermaids and Musicians', 'Black Bird Bookstore (4541 Irving St)', '2025-10-23', '2025-10-24 02:00:00+00', NULL, 'Author Reading/Q&A', 'Meet local author Diane Frank for a reading from her new novel Mermaids and Musicians, with discussion and book signing. Free event; copies of the book available for purchase.', 'approved');

-- Friday, October 24, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Early Childhood Music Class', 'Outer Village (1314 8th Ave)', '2025-10-24', '2025-10-24 17:15:00+00', '2025-10-24 18:00:00+00', 'Kids/Family Music', 'Little Ladybugs music class for infants to 5-year-olds and their caregivers, led by Music with Toby. Includes singing, movement, percussion instruments, and dancing with scarves, accompanied by violin. Registration: Drop-in or series enrollment (check Outer Village).', 'approved'),
('ByTheWay Pizza Pop-Up', 'Daymoon Bakery (3928 Irving St)', '2025-10-24', '2025-10-24 16:00:00+00', '2025-10-24 22:00:00+00', 'Food/Pop-Up', 'Special one-day pop-up featuring ByTheWay Pizza (gluten-free artisan pizza) at Daymoon Bread. Pizzas available for purchase during the bakery''s normal Friday hours (morning until sell-out).', 'approved'),
('Usal Project Pop-Up', 'The Last Straw (4540 Irving St)', '2025-10-24', '2025-10-24 19:00:00+00', '2025-10-27 01:00:00+00', 'Retail Pop-Up', 'Usal Project (modern outdoor-enthusiast apparel and goods) is hosting a pop-up shop as part of their SF residency. Browse apparel and gear at The Last Straw gallery/shop in the Outer Sunset. Open Friday through Sunday, 12-6pm.', 'approved'),
('Movie Night in McCoppin: The Wild Robot', 'McCoppin Square (Taraval St @ 23rd Ave)', '2025-10-24', '2025-10-25 00:30:00+00', NULL, 'Outdoor Family Movie', 'Movies in McCoppin free film screening under the stars. This week''s movie is "The Wild Robot" (animated family film). Free popcorn, snacks, and family fun provided by People of Parkside Sunset. Tip: Bring blankets and chairs; costumes welcome (Halloween theme).', 'approved'),
('SuperNatural Halloween at Cal Academy', 'California Academy of Sciences (Golden Gate Park)', '2025-10-24', '2025-10-25 01:30:00+00', '2025-10-25 04:00:00+00', 'Family Museum Night', 'A spooky evening at the Academy featuring a silent disco in the aquarium, live "mad science" demos, trick-or-treat stations, a costume parade, face painting, and more. Tickets: $40–$200 (pre-registration required; includes museum entry).', 'approved');

-- Saturday, October 25, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Storytime with Olive the Storyteller', 'Outer Village (1314 8th Ave)', '2025-10-25', '2025-10-25 17:15:00+00', NULL, 'Kids Storytime', 'A magical storytelling session for young children hosted by Olive the Storyteller at the Outer Village community space. Free; families welcome (no RSVP required).', 'approved'),
('Sunset Dunes Park Snowy Plovers Talk', 'Sunset Dunes Park @ Judah St entrance', '2025-10-25', '2025-10-25 17:00:00+00', '2025-10-25 19:00:00+00', 'Nature/Education', 'Western Snowy Plover Habitat Stewards meetup on the beach, led by park volunteers. Features a brief talk about the local snowy plovers and their habitat, a spotting scope to view the birds up close, and an optional mini beach cleanup walk. Cost: Free (gloves, buckets provided if participating in cleanup; bring layers and sunscreen).', 'approved'),
('43rd Annual Sandcastle Classic', 'Ocean Beach (Great Hwy @ Balboa St)', '2025-10-25', '2025-10-25 18:00:00+00', '2025-10-25 22:30:00+00', 'Family Festival/Competition', 'San Francisco''s famous sand sculpture competition on Ocean Beach. Local K–12 students team up with architects and engineers to build giant sandcastles with video game themes. Enjoy music and dance performances, a community sandcastle-building area, and food trucks on site. Cost: Free to attend (donations support arts education).', 'approved'),
('Boo at the Zoo (Day 1)', 'San Francisco Zoo (Sloat Blvd @ Great Hwy)', '2025-10-25', '2025-10-25 18:00:00+00', '2025-10-25 23:00:00+00', 'Holiday/Family', 'The Zoo''s annual Halloween celebration. Costume parade at the playground, a seasonal hay maze, live entertainment, treat stations, and special pumpkin feedings for many zoo animals. Included with zoo admission (online reservation recommended).', 'approved');

-- Sunday, October 26, 2025
INSERT INTO events (title, location, event_date, start_time, end_time, event_type, description, status) VALUES
('Outer Sunset Farmers Market & Mercantile', '37th Ave (between Ortega & Quintara)', '2025-10-26', '2025-10-26 16:00:00+00', '2025-10-26 21:00:00+00', 'Community Market', 'Weekly open-air market featuring farm-fresh produce and local goods. Fresh produce, artisanal foods, food trucks, local crafts and makers, live music, and kids'' activities. Family-friendly and free to attend. (Street closure on 37th Ave; plenty of vendors to explore.)', 'approved'),
('Mat Yoga on the Great Highway', 'Sunset Dunes Great Hwy @ Judah', '2025-10-26', '2025-10-26 19:00:00+00', '2025-10-26 20:00:00+00', 'Wellness/Exercise', 'Outdoor yoga class (bring your mat) as part of the Sundays at the Beach series. All levels welcome. Meets at noon on the Great Highway pedestrian area at Judah. Free; no sign-up needed (weather permitting).', 'approved'),
('The Great Hauntway', 'Sunset Dunes Park (Great Hwy, Judah–Taraval)', '2025-10-26', '2025-10-26 20:00:00+00', '2025-10-27 01:00:00+00', 'Holiday/Festival', 'A massive family-friendly Halloween festival along the car-free Great Highway park. Enjoy over a mile of trick-or-treating with local vendors, live entertainment, bounce houses, big bubbles, pumpkin decorating, music and more. Cost: Free admission. Come in costume! (Organized by Friends of Sunset Dunes Park – fifth annual event).', 'approved'),
('Boo at the Zoo (Day 2)', 'San Francisco Zoo (Sloat Blvd @ Great Hwy)', '2025-10-26', '2025-10-26 18:00:00+00', '2025-10-26 23:00:00+00', 'Holiday/Family', 'Halloween at the Zoo continues – costume parade, animal pumpkin treats, hay maze, performances and candy for the kids. Included with zoo admission (online reservation recommended).', 'approved');